### ISSUE TITLE
newly created folder does not appear in the UI until some other action has occurred on the page

### ISSUE THREAD

**Issue by ejones40** [gaiin-platform/amplify-genai-frontend#6]
As described in the title, new folders don't appear until another action is taken (refresh, navigation, etc.).

Bug can be replicated using Safari/Chrome/Firefox on a Mac.

![image](https://github.com/user-attachments/assets/3b8b909d-b77c-4065-b830-27648049a9bf)

![image](https://github.com/user-attachments/assets/7e35e249-e6a3-4f31-afbc-1edef1d738d4)

**Comment by karnsab** [comment]
resolved in v0.6.0
